### ISSUE TITLE
Windows bots failures

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package-bots#3]
I have been seeing this failure a lot recently on the windows bots, and it makes it hard to track actual failures:

```
Unhandled exception:
Uncaught Error: FileSystemException: Cannot delete file, path = '.flaky.log' (OS Error: The process cannot access the file because it is being used by another process.

, errno = 32)
Stack Trace:
#0      _File.throwIfError (dart:io/file_impl.dart:558)
#1      _File._deleteSync (dart:io/file_impl.dart:305)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:406)
#3      testConfigurations (file:///E:/b/build/slave/packages-windows-polymer-dart/build/dart/tools/testing/dart/test_configurations.dart:84:24)
#4      main.<anonymous closure> (file:///E:/b/build/slave/packages-windows-polymer-dart/build/dart/tools/test.dart:64:25)
#5      _RootZone.runUnary (dart:async/zone.dart:1155)
#6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#7      _Future._propagateToListeners (dart:async/future_impl.dart:567)
#8      _Future._completeWithValue (dart:async/future_impl.dart:358)
#9      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#10     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#11     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#12     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

**Comment by sigmundch** [comment]
@ricowind, any ideas?

**Comment by jakemac53** [comment]
fyi, this is reproducing consistently when the polymer tests run

**Comment by ricowind** [comment]
cl to fix:
https://chromiumcodereview.appspot.com/1077563002

**Comment by sigmundch** [comment]
thanks Rico!
